# Generated by Django 3.1.7 on 2021-03-13 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_books',
            name='id_profile',
            field=models.ForeignKey(help_text='Usuario que leyó el libro', on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='Nombre'),
        ),
    ]
