# Generated by Django 3.1.7 on 2021-03-06 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del libro', max_length=80, verbose_name='Título')),
                ('author', models.CharField(help_text='Autor del libro.', max_length=80, verbose_name='Autor')),
                ('year', models.PositiveIntegerField(blank=True, help_text='Año en que se publico el libro.', null=True, verbose_name='Año de publicación')),
                ('pages', models.PositiveIntegerField(blank=True, help_text='Cantidad de hojas que tiene el libro.', null=True, verbose_name='Cantidad de Hojas')),
                ('img_cover', models.ImageField(blank=True, upload_to='books')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
            },
        ),
        migrations.CreateModel(
            name='Users_Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_date', models.DateField(blank=True, help_text='Fecha en la que se leyó el libro', null=True, verbose_name='Fecha Leido')),
                ('review', models.TextField(blank=True, help_text='Breve reseña del libro leido.', max_length=500, null=True, verbose_name='Reseña')),
                ('id_book', models.ForeignKey(help_text='Nombre del libro leido', on_delete=django.db.models.deletion.CASCADE, to='books.books', verbose_name='Libro')),
                ('id_profile', models.OneToOneField(help_text='Usuario que leyó el libro', on_delete=django.db.models.deletion.CASCADE, to='users.profile', verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Libro leido',
                'verbose_name_plural': 'Libros leidos',
            },
        ),
    ]
