# Generated by Django 3.1.7 on 2021-03-07 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='img_cover',
            field=models.ImageField(blank=True, help_text='Imagen de la portada', null=True, upload_to='books', verbose_name='Portada'),
        ),
    ]
