# Generated by Django 3.1.7 on 2021-03-13 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210307_0042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users_Books',
        ),
    ]
